--- 
- name: Create redhat directory in /home
  file:
      path: /home/redhat
      state: directory

- name : i want to download tomcat 10
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
    dest: /home/redhat/tmp
    force_basic_auth: yes

- name: i want to create tomcat directory
  file: 
   path: /opt/tomcat
   state: directory 

- name: i want to exact the tomcat file 
  command:
    cmd: sudo tar xzvf /home/redhat/tmp -C /opt/tomcat --strip-components=1
    creates: /opt/redhat/LICENSE