---
- name: i want to update
  apt: 
    update_cache: yes

- name: Install OpenJDK 11
  hosts: all
  become: true
  block:
  - name: Install OpenJDK 11 using yum
    yum:
      name: java-11-openjdk-devel
      state: present
 